# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799b3763e280cdda9140a7029ee33ac89f4bd994be920fc874e7b4a791586b99eb5383afe11b605c8d02a1dd020e71fc2b6567673557fc9b81922762ea8533b9

test:
  secret_key_base: fac80b50c1b28e3a99b332aba01f09e80b520ae479c41ad064a5ae7907a3646c239549871e14826f2914f16ff5b7314aa0f51faa4e431fbccee545ca624f3cdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
